### ISSUE TITLE
Why 2 level of data?

### ISSUE THREAD

**Issue by shailpurohit** [vinitsolanki/todo-application#4]
https://github.com/vinitsolanki/todo-application/blob/5e59d0716ec9a01a006117d11af1f42f97619eee/todo-angular-app/script/todoController.js#L49

**Comment by vinitsolanki** [comment]
response is a instance of angular's `HttpPromise` and it has below properties
1. data 
2. status 
3.headers 
4.config 
5.statusText 
6.xhrStatus 

If we want to collect the data sent from the API, we should use `response.data` and this will be GenericResponseBean( as JSON).
GenericResponseBean has few properties (e.g. error, messageKey, localizedMessage and data).
So response.data.data have list of all users which respond by the API.
